name: Elixir Plug package CI

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
  schedule:
    - cron: "0 0 * * 1-5"

jobs:
  lint_git:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'schedule' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: lintje/action@v0.11

  lint_format:
    runs-on: ubuntu-latest
    env:
      PLUG_VERSION: "~> 1.18"
    steps:
      - name: Set up Erlang and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 27.x
          elixir-version: latest
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check code formatting
        run: mix format --check-formatted

  lint_credo:
    runs-on: ubuntu-latest
    env:
      PLUG_VERSION: "~> 1.18"
    steps:
      - name: Set up Erlang and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 27.x
          elixir-version: latest
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get dependencies
        run: mix deps.get
      - name: Analyze code with Credo
        run: mix credo --strict

  lint_compile:
    runs-on: ubuntu-latest
    env:
      PLUG_VERSION: "~> 1.18"
    steps:
      - name: Set up Erlang and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 27.x
          elixir-version: latest
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get dependencies
        run: mix deps.get
      - name: Check for compilation errors
        run: mix compile --warnings-as-errors

  lint_dialyzer:
    runs-on: ubuntu-latest
    env:
      PLUG_VERSION: "~> 1.18"
    steps:
      - name: Set up Erlang and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 27.x
          elixir-version: 1.17.x
      - name: PLT cache
        uses: actions/cache@v4
        id: plt_cache
        with:
          key: plt
          path: priv/plts
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get dependencies
        run: mix deps.get
      - name: Compile
        run: mix compile
      - name: Analyze code with Dialyzer
        run: mix dialyzer --format github

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        elixir:
          - 1.17.x
        otp:
          - 27.x
          - 26.x
          - 25.x
        plug:
          - "~> 1.18"
          - "~> 1.17"
        include:
          - elixir: main
            otp: 27.x
            plug: "~> 1.18"
          - elixir: latest
            otp: 27.x
            plug: "~> 1.18"
          - elixir: 1.16.x
            otp: 26.x
            plug: "~> 1.17"
          - elixir: 1.15.x
            otp: 26.x
            plug: "~> 1.17"
          - elixir: 1.14.x
            otp: 25.x
            plug: "~> 1.17"
          - elixir: 1.13.x
            otp: 24.x
            plug: "~> 1.17"
          - elixir: 1.12.x
            otp: 24.x
            plug: "~> 1.17"
          - elixir: 1.11.x
            otp: 24.x
            plug: "~> 1.17"

    env:
      PLUG_VERSION: ${{matrix.plug}}
    steps:
      - name: Set up Erlang and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
